from conectando_banco_de_dados import conectando_ao_banco



def consulta_dados_banco(date_inicial: str, date_final: str, parametros_query):
    
    cursor = conectando_ao_banco()
    print('\n')
    print('Carregando banco de dados, aguarde: \n')
    

    var_query = f"""
    SELECT        
	FORMAT(DATA,'dd/MM/yyyy') AS DATA,
    FORMAT(DATA,'HH:mm:ss') as HORA,
	ARQUIVO AS ARQUIVO,
	DURACAO AS DURACAO,
	CPF_OPERADOR AS CPF,
	NOME AS TABULACAO,
	ORIGEM AS ORIGEM,
	'CPC' AS TIPO ,
	RIGHT(TELEFONE,11) AS TELEFONE,
	CONTRATO AS CONTRATO,
	ASSESSORIA AS ASSESSORIA,
	NOME_OPERADOR AS NOME
	FROM OPENQUERY (TOTALIP,
	'SELECT B.DATA,
	NULL AS ARQUIVO,
	B.DURACAO,
	NULL AS CPF_OPERADOR,
	NULL AS NOME_OPERADOR,
	C.NOME,
	''RECEPTIVO'' AS ORIGEM,
	A.ID_STATUS_LIGACAO AS OCOR,
	NULL TIPO_OCOR,
	B.ORIGEM AS TELEFONE,
	NULL AS CONTRATO,
	''ICR'' AS ASSESSORIA
	FROM HISTORICOS_ATIVOS_RECEPTIVOS A
	INNER JOIN LIGACOES_RECEPTIVO B ON A.ID_LIGACOES_RECEPTIVO = B.ID
	INNER JOIN STATUS_LIGACAO C ON A.ID_STATUS_LIGACAO = C.ID
	WHERE A.ID_STATUS_LIGACAO NOT IN ({parametros_query[0]})
	AND A.DATA BETWEEN ''{date_inicial}'' AND ''{date_final}''
	') A

	UNION 
	-- LIGAÇÕES ATIVO
	SELECT        
	FORMAT(DATA,'dd/MM/yyyy'),
    FORMAT(DATA,'HH:mm:ss'),
	ARQUIVO  ,
	DURACAO  ,
	CPF_OPERADOR  ,
	NOME,
	ORIGEM,
	'CPC',
	RIGHT(TELEFONE,11),
	CONTRATO,
	ASSESSORIA ,
	NOME_OPERADOR
	FROM OPENQUERY (TOTALIP,
	'SELECT B.DATA,
	NULL AS ARQUIVO,
	B.DURACAO,
	NULL AS CPF_OPERADOR,
	NULL AS NOME_OPERADOR,
	A.ID_STATUS_LIGACAO AS OCOR,
	C.NOME,
	''ATIVO'' AS ORIGEM,
	NULL TIPO_OCOR,
	B.DESTINO AS TELEFONE,
	NULL AS CONTRATO,
	''ICR'' AS ASSESSORIA
	FROM HISTORICOS_ATIVOS_RECEPTIVOS A
	INNER JOIN LIGACOES_ATIVO B ON A.ID_LIGACOES_ATIVO = B.ID
	INNER JOIN STATUS_LIGACAO C ON A.ID_STATUS_LIGACAO = C.ID
	WHERE A.ID_STATUS_LIGACAO NOT IN ({parametros_query[1]})
	AND A.DATA BETWEEN ''{date_inicial}'' AND ''{date_final}''
	') B

	union
	--LIGAÇÕES DISCADOR
	SELECT DISTINCT	
	FORMAT(DATA_HORA_INICIO,'dd/MM/yyyy') AS DATA,
    FORMAT(DATA_HORA_INICIO,'HH:mm:ss') as HORA,
	ARQUIVO AS ARQUIVO,
	DURACAO AS DURACAO,
	CPF AS CPF,
	STATUS_NOME AS TABULACAO,
	ORIGEM AS ORIGEM,
	'CPC' AS TIPO ,
	RIGHT(TELEFONE,11) AS TELEFONE,
	CONTRATO AS CONTRATO,
	ASSESSORIA AS ASSESSORIA,
	NOME_OPERADOR AS NOME
	FROM OPENQUERY (TOTALIP, 'SELECT DATA_HORA_INICIO,
	NULL AS ARQUIVO,
	B.DURACAO,
	NULL AS CPF,
	STATUS_ID AS OCOR,
	STATUS_NOME,
	''DISCADOR'' AS ORIGEM,
	''CPC'' AS TIPO,
	TELEFONE,
	NULL AS CONTRATO,
	''ICR'' AS ASSESSORIA,
	NULL AS NOME_OPERADOR
	FROM RESULTADO_DISCADOR_MENSAL A 
	INNER JOIN LIGACOES_ATIVO B ON A.UNIQUEID = B.UNIQUEID
	WHERE STATUS_ID NOT IN ({parametros_query[2]})
	AND A.DATA_HORA_INICIO BETWEEN ''{date_inicial}'' AND ''{date_final}''
	;')
    """
    

    cursor.execute(var_query)
    return cursor.fetchall()




